name: Run Colab + Cloudflare Tunnel

on:
  schedule:
    - cron: "0 */6 * * *"   # Every 6 hours
  workflow_dispatch:

jobs:
  run-colab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run notebook in Colab
        uses: nturley/run-colab@v1
        with:
          path: cloud_run.ipynb
