'''name: Start Colab LLM

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Colab via web URL
      run: |
        curl -X POST https://api.colab.research.google.com/drive/your_notebook_id_here
'''
